@echo off
cd /d "d:\My project"
echo Initializing git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Renaming branch...
git branch -M main
echo Adding remote...
git remote add origin https://github.com/chau2512/test.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
